import React from 'react';
import {
  Landmark,
  Wallet,
  User,
  UserPlus,
  UserMinus,
  UserCheck,
  Users,
  Plus,
  PlusSquare,
  PlusCircle,
  Camera,
  ImagePlus,
  Image,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Building2,
  Apple,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Paperclip,
  Sparkles,
  Wand2,
  Badge,
  BadgeCheck,
  Ban,
  Zap,
  ZapOff,
  PhoneCall,
  X,
  XCircle,
  MessageSquare,
  MessageSquareText,
  Check,
  CheckCircle2,
  CheckCheck,
  Contact,
  Copy,
  Clipboard,
  CreditCard,
  Crop,
  Banknote,
  Coins,
  Trash2,
  FileText,
  FileEdit,
  Download,
  Edit3,
  AlertCircle,
  AlertTriangle,
  AlertOctagon,
  Smile,
  Flag,
  FolderOpen,
  FolderSync,
  Scale,
  Star,
  StarHalf,
  HelpCircle,
  History,
  Home,
  Hourglass,
  Lock,
  Key,
  KeyRound,
  Info,
  Share2,
  Lightbulb,
  Link,
  MapPin,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  Send,
  Menu,
  MoreVertical,
  Bell,
  BellRing,
  Palette,
  Clock,
  CalendarClock,
  Smartphone,
  Receipt,
  Loader2,
  Brain,
  Globe,
  RefreshCw,
  RotateCcw,
  Rocket,
  Save,
  GraduationCap,
  Search,
  ShoppingBag,
  Layers,
  Headset,
  Table,
  Timer,
  Languages,
  TrendingUp,
  Sliders,
  Upload,
  Eye,
  EyeOff,
  Webhook,
  Briefcase,
  ZoomIn,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  LucideProps,
} from 'lucide-react';

export type IconName = string;

export interface IconProps extends LucideProps {
  name: IconName;
  title?: string;
  [key: string]: any;
}

const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  // Financial & Banking
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  credit_card: CreditCard,
  payments: Coins,
  currency_exchange: Banknote,
  price_check: Receipt,
  receipt_long: Receipt,

  // Users & Auth
  person: User,
  person_add: UserPlus,
  person_check: UserCheck,
  person_remove: UserMinus,
  account_box: User,
  group: Users,
  family_restroom: Users,
  switch_account: UserCheck,
  lock: Lock,
  lock_person: UserCheck,
  lock_reset: KeyRound,
  https: Lock,
  key: Key,
  vpn_key: Key,
  login: LogIn,
  logout: LogOut,
  admin_panel_settings: ShieldAlert,
  security: ShieldCheck,
  verified_user: ShieldCheck,
  verified: BadgeCheck,
  badge: Badge,
  face: Smile,

  // Actions & Controls
  add: Plus,
  add_box: PlusSquare,
  add_circle: PlusCircle,
  close: X,
  cancel: XCircle,
  block: Ban,
  check: Check,
  check_circle: CheckCircle2,
  task_alt: CheckCircle2,
  done_all: CheckCheck,
  delete: Trash2,
  delete_forever: Trash2,
  edit: Edit3,
  edit_document: FileEdit,
  edit_note: FileEdit,
  save: Save,
  refresh: RotateCcw,
  replay: RotateCcw,
  sync: RefreshCw,
  published_with_changes: RefreshCw,
  search: Search,
  tune: Sliders,
  zoom_in: ZoomIn,

  // Navigation & Direction
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  chevron_down: ChevronDown,
  chevron_up: ChevronUp,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  menu: Menu,
  menu_open: Menu,
  more_vert: MoreVertical,
  home: Home,

  // Files & Media
  description: FileText,
  feed: FileText,
  picture_as_pdf: FileText,
  contact_page: Contact,
  content_copy: Copy,
  content_paste: Clipboard,
  image: Image,
  crop: Crop,
  add_a_photo: Camera,
  add_photo_alternate: ImagePlus,
  attach_file: Paperclip,
  upload_file: Upload,
  download: Download,
  download_done: Check,
  install_mobile: Download,
  ios_share: Share2,
  folder_open: FolderOpen,
  folder_shared: FolderSync,
  table_view: Table,

  // Communication & Status
  mail: Mail,
  mark_email_read: MailCheck,
  sms: MessageSquare,
  chat: MessageSquare,
  mark_chat_read: MessageSquareText,
  send: Send,
  call: PhoneCall,
  phone_iphone: Smartphone,
  phone_android: Smartphone,
  smartphone: Smartphone,
  notifications: Bell,
  notifications_active: BellRing,
  support_agent: Headset,
  rate_review: StarHalf,
  star: Star,
  grade: Star,
  stars: Sparkles,

  // Intelligence, AI & Creation
  auto_awesome: Sparkles,
  auto_fix_high: Wand2,
  magic_button: Sparkles,
  psychology: Brain,
  lightbulb: Lightbulb,
  rocket_launch: Rocket,
  palette: Palette,
  style: Layers,

  // Utilities, Alerts & Feedback
  bolt: Zap,
  offline_bolt: ZapOff,
  info: Info,
  help: HelpCircle,
  warning: AlertTriangle,
  error: AlertCircle,
  priority_high: AlertOctagon,
  gpp_maybe: ShieldAlert,
  policy: FileText,
  flag: Flag,
  gavel: Scale,
  link: Link,
  location_on: MapPin,
  apartment: Building2,
  public: Globe,
  apple: Apple,
  schedule: Clock,
  history: History,
  hourglass_top: Hourglass,
  pending_actions: CalendarClock,
  timer: Timer,
  school: GraduationCap,
  shopping_bag: ShoppingBag,
  translate: Languages,
  trending_up: TrendingUp,
  progress_activity: Loader2,
  webhook: Webhook,
  work: Briefcase,
  work_history: History,
  work_off: Briefcase,
  shield: Shield,
  visibility: Eye,
  visibility_off: EyeOff,
};

export const Icon: React.FC<IconProps> = ({
  name,
  className = '',
  size = 18,
  ...props
}) => {
  const cleanName = (name || '').trim();
  const Component = ICON_MAP[cleanName] || Sparkles;

  return (
    <Component
      className={`inline-block shrink-0 align-middle ${className}`}
      size={size}
      aria-hidden="true"
      {...props}
    />
  );
};

export default Icon;
